# Generated by Django 5.2.1 on 2025-06-20 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('laminator_code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FilamentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament_manager.brand')),
            ],
            options={
                'unique_together': {('brand', 'material')},
            },
        ),
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('ral', models.CharField(blank=True, max_length=10, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament_manager.brand')),
                ('filament_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament_manager.filamenttype')),
            ],
        ),
        migrations.CreateModel(
            name='FilamentConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('flow', models.FloatField()),
                ('pressure_advance', models.FloatField()),
                ('retraction_distance', models.FloatField()),
                ('bed_temperature', models.FloatField()),
                ('filament_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament_manager.filamenttype')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament_manager.printer')),
            ],
            options={
                'unique_together': {('filament_type', 'printer')},
            },
        ),
        migrations.CreateModel(
            name='ColorChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_1_to_2', models.FloatField()),
                ('value_2_to_1', models.FloatField()),
                ('filament_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_change_filament_1', to='filament_manager.filament')),
                ('filament_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_change_filament_2', to='filament_manager.filament')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filament_manager.printer')),
            ],
            options={
                'unique_together': {('filament_1', 'filament_2', 'printer')},
            },
        ),
    ]
